#!/bin/bash
# Agent Sync System - Keep package in sync with global agents

GLOBAL_AGENTS_DIR="$HOME/.claude/agents"
PACKAGE_AGENTS_DIR="$(dirname "$0")/agents"
PACKAGE_LIB_DIR="$(dirname "$0")/lib"
GLOBAL_LIB_DIR="$HOME/Projects/Claude-Agentic-Files/lib"

echo "🔄 Syncing agents from global to package..."

# Create package directories if they don't exist
mkdir -p "$PACKAGE_AGENTS_DIR"

# Copy agents from global to package
AGENTS=("marketing-cmo" "fundraising-cro" "content-creator" "financial-cfo" "product-cpo")

for agent in "${AGENTS[@]}"; do
    if [ -f "$GLOBAL_AGENTS_DIR/${agent}.md" ]; then
        echo "📄 Syncing ${agent}..."
        cp "$GLOBAL_AGENTS_DIR/${agent}.md" "$PACKAGE_AGENTS_DIR/"
        
        # Update version number in frontmatter
        VERSION=$(date +%Y.%m.%d)
        sed -i "s/version: .*/version: \"$VERSION\"/" "$PACKAGE_AGENTS_DIR/${agent}.md" 2>/dev/null || true
        
        echo "   ✅ Updated to version $VERSION"
    else
        echo "   ❌ ${agent}.md not found in global agents"
    fi
done

# Sync automation scripts
echo "🛠️  Syncing automation scripts..."
if [ -d "$GLOBAL_LIB_DIR" ]; then
    rsync -av "$GLOBAL_LIB_DIR/" "$PACKAGE_LIB_DIR/"
    echo "   ✅ Library scripts synced"
else
    echo "   ⚠️  Global lib directory not found: $GLOBAL_LIB_DIR"
fi

# Generate changelog
echo "📝 Generating changelog..."
cat > CHANGELOG.md << EOF
# Changelog

## [$(date +%Y.%m.%d)] - $(date +%Y-%m-%d)

### Added
- Synced all agents from global Claude installation
- Updated automation scripts with latest improvements

### Agents Updated
$(for agent in "${AGENTS[@]}"; do
    if [ -f "$GLOBAL_AGENTS_DIR/${agent}.md" ]; then
        echo "- ${agent}: Latest improvements from global installation"
    fi
done)

### Scripts Updated  
$(ls "$PACKAGE_LIB_DIR"/*.sh 2>/dev/null | xargs -I {} basename {} | sed 's/^/- /')

---
*Auto-generated by sync-agents.sh*
EOF

echo "✅ Sync complete! Package is now up-to-date with your global agents."
echo ""
echo "Next steps:"
echo "1. Review changes: git diff"
echo "2. Test package: ./setup/verify-installation.sh"  
echo "3. Commit and push: git add . && git commit -m 'Sync agents $(date +%Y-%m-%d)'"